---
- hosts: webservers
  become: yes
  tasks:
  - name: "update app cache and install nginx"
    apt:
      name: nginx
      state: latest
      update_cache: yes

#  - name: "create www directory"
#    file:
#      path: /var/www/example.com
#      state: directory
#      mode: '0775'
#      owner: ansible
#      group: ansible
  
#  - name: "remove default site"
#    file:
#      path: /etc/nginx/sites-enabled/default
#      state: absent
#    notify: restart nginx
  
  - name: "Apply nginx config"
    template:
      src: files/nginx.config.j2
      dest: /etc/nginx/sites-available/default
    notify: restart nginx  
      
  - name:  "copy custom 404"  
    ansible.builtin.copy:
      src: files/custom_404.html
      dest: /usr/share/nginx/html/

  - name: "start nginx at reboot"
    systemd:
      name: nginx
      enabled: yes
      masked: no
  
  - name: "Allow Access 3200"
    ufw:
      rule: allow
      port: '3200'
      proto: tcp

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted