---
- hosts: webservers
  become: yes
  tasks:
  - name: "update app cache and install nginx"
    apt:
      name: nginx
      state: latest
      update_cache: yes
  
  - name: "Apply nginx config"
    template:
      src: config/nginx.config.j2
      dest: /etc/nginx/sites-available/default
    notify: restart nginx  
      
  - name:  "copy custom 404"  
    ansible.builtin.copy:
      src: html/
      dest: /usr/share/nginx/html/
      directory_mode: yes

  - name: "start nginx at reboot"
    systemd:
      name: nginx
      enabled: yes
      masked: no
  
  - name: "Allow Access 3200"
    ufw:
      rule: allow
      port: '3200'
      proto: tcp

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted